export const initialHeapSortAnimationNodes = [
  {
    id: '1',
    data: {
      value: 1,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableStart: false,
      isConnectableEnd: true,
      isSorted: false,
    },
    position: { x: 145, y: 10 },
    type: 'textUpdater',
  },
  {
    id: '2',
    data: {
      value: 2,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: true,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 75, y: 100 },
    type: 'textUpdater',
  },
  {
    id: '3',
    data: {
      value: 3,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: true,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 210, y: 100 },
    type: 'textUpdater',
  },
  {
    id: '4',
    data: {
      value: 4,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: true,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 30, y: 180 },
    type: 'textUpdater',
  },
  {
    id: '5',
    data: {
      value: 5,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: true,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 120, y: 180 },
    type: 'textUpdater',
  },
  {
    id: '6',
    data: {
      value: 6,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: false,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 180, y: 180 },
    type: 'textUpdater',
  },
  {
    id: '7',
    data: {
      value: 7,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: false,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 240, y: 180 },
    type: 'textUpdater',
  },
  {
    id: '8',
    data: {
      value: 8,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: false,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 0, y: 260 },
    type: 'textUpdater',
  },
  {
    id: '9',
    data: {
      value: 9,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: false,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 60, y: 260 },
    type: 'textUpdater',
  },
  {
    id: '10',
    data: {
      value: 10,
      isYellow: false,
      isRed: false,
      isBlue: false,
      isFocused: false,
      isDisabled: true,
      isConnectableEnd: false,
      isConnectableStart: true,
      isSorted: false,
    },
    position: { x: 120, y: 260 },
    type: 'textUpdater',
  },
];

export const heapSortAnimationEdges = [
  { id: '1-2', source: '1', target: '2', type: 'custom-edge' },
  { id: '1-3', source: '1', target: '3', type: 'custom-edge' },
  { id: '3-6', source: '3', target: '6', type: 'custom-edge' },
  { id: '3-7', source: '3', target: '7', type: 'custom-edge' },
  { id: '2-4', source: '2', target: '4', type: 'custom-edge' },
  { id: '2-5', source: '2', target: '5', type: 'custom-edge' },
  { id: '4-8', source: '4', target: '8', type: 'custom-edge' },
  { id: '4-9', source: '4', target: '9', type: 'custom-edge' },
  { id: '5-10', source: '5', target: '10', type: 'custom-edge' },
];
