name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Specify the version of Node.js here

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js (specify the version you're using)
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Cache node_modules to speed up builds
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Lint the project (using eslint)
    #- name: Lint code
      #run: npm run lint

    # Run tests (if you have a test script)
    #- name: Run tests
      #run: npm run test

    # Build the project
    - name: Build project
      run: npm run build
